CREATE TABLE IF NOT EXISTS pedidos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cliente_nome VARCHAR(150) NOT NULL,
  carro_id INT UNSIGNED     NOT NULL,
  quantidade INT UNSIGNED   NOT NULL DEFAULT 1,
  preco_unitario DECIMAL(10,2) NOT NULL,
  data_pedido DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  criado_em TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (carro_id) REFERENCES carros(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;